In [1]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

chunck_size=500
# File to Load (Remember to Change These)
nyc_zillow_load = "\\Users\\Paul-DS\\Downloads\\Neighborhood_MedianValuePerSqft_AllHomes.csv"
nyc_crime_load="\\Users\\Paul-DS\\Downloads\\NYPD_Complaint_Data_Historic.csv"

nyc_zillow_data=pd.read_csv(nyc_zillow_load, low_memory=True)
nyc_crime_data=pd.read_csv(nyc_crime_load, low_memory=True)



In [2]:
#nyc_crime_data.set_index('RPT_DT').groupby(pd.TimeGrouper('M')).mean().dropna()

In [3]:
nyc_crime_data.columns

Index(['CMPLNT_NUM', 'CMPLNT_FR_DT', 'CMPLNT_FR_TM', 'CMPLNT_TO_DT',
       'CMPLNT_TO_TM', 'RPT_DT', 'KY_CD', 'OFNS_DESC', 'PD_CD', 'PD_DESC',
       'CRM_ATPT_CPTD_CD', 'LAW_CAT_CD', 'JURIS_DESC', 'BORO_NM',
       'ADDR_PCT_CD', 'LOC_OF_OCCUR_DESC', 'PREM_TYP_DESC', 'PARKS_NM',
       'HADEVELOPT', 'X_COORD_CD', 'Y_COORD_CD', 'Latitude', 'Longitude',
       'Lat_Lon'],
      dtype='object')

In [4]:
nyc_crime_data['PREM_TYP_DESC'].unique()

array(['BAR/NIGHT CLUB', nan, 'OTHER', 'RESIDENCE-HOUSE', 'DRUG STORE',
       'STREET', 'RESIDENCE - APT. HOUSE', 'FAST FOOD',
       'RESTAURANT/DINER', 'DRY CLEANER/LAUNDRY', 'PUBLIC BUILDING',
       'RESIDENCE - PUBLIC HOUSING', 'PARK/PLAYGROUND',
       'PARKING LOT/GARAGE (PUBLIC)', 'GAS STATION', 'TUNNEL',
       'CHAIN STORE', 'CHECK CASHING BUSINESS', 'TRANSIT - NYC SUBWAY',
       'BUS (NYC TRANSIT)', 'BEAUTY & NAIL SALON', 'GROCERY/BODEGA',
       'COMMERCIAL BUILDING', 'FOOD SUPERMARKET', 'HOTEL/MOTEL',
       'SMALL MERCHANT', 'CHURCH', 'PARKING LOT/GARAGE (PRIVATE)',
       'DEPARTMENT STORE', 'STORE UNCLASSIFIED', 'GYM/FITNESS FACILITY',
       'VARIETY STORE', 'CLOTHING/BOUTIQUE', 'FERRY/FERRY TERMINAL',
       'DOCTOR/DENTIST OFFICE', 'TELECOMM. STORE', 'JEWELRY',
       'CONSTRUCTION SITE', 'BUS STOP', 'BANK', 'HOSPITAL',
       'TAXI (LIVERY LICENSED)', 'ATM', 'BRIDGE',
       'PRIVATE/PAROCHIAL SCHOOL', 'SOCIAL CLUB/POLICY', 'CANDY STORE',
       'FACTORY/WAREHOUSE

In [5]:
nyc_crime_data['PARKS_NM'].unique() # NOT MUCH DATA

array([nan, 'MADISON SQUARE PARK', 'COLUMBUS PARK AT MANHATTAN', ...,
       'ARSENAL NORTH', 'MADISON SQUARE GARDEN ASSOCIATION',
       'BROAD CHANNEL PARK'], dtype=object)

In [6]:
nyc_crime_data['HADEVELOPT'].unique()

array([nan, 'MARCY', 'UNION AVENUE-EAST 166TH STREET', 'MORRIS I',
       'FARRAGUT', 'LA GUARDIA', 'BORINQUEN PLAZA I', 'REDFERN',
       'BOSTON SECOR', 'RED HOOK WEST', 'RICHMOND TERRACE', 'LINDEN',
       'STAPLETON', '830 AMSTERDAM AVENUE', 'SOUNDVIEW', 'WOODSIDE',
       'BARUCH', 'BEDFORD-STUYVESANT REHAB', 'RUTGERS', 'CASTLE HILL',
       'TOMPKINS', 'WILLIAMSBURG', 'BUSHWICK II (GROUPS B & D)',
       'GUN HILL', 'BELMONT-SUTTER AREA', 'BUTLER', 'GRANT', 'GLENWOOD',
       'DOUGLASS', 'THROGGS NECK', 'SOUTH BEACH', 'JACKSON', 'VAN DYKE I',
       'EASTCHESTER GARDENS', 'WEEKSVILLE GARDENS',
       'ATLANTIC TERMINAL SITE 4B', '1471 WATSON AVENUE', 'FOREST',
       'WILLIAMS PLAZA', '303 VERNON AVENUE',
       'WEST TREMONT REHAB (GROUP 3)', 'BAY VIEW', "MARINER'S HARBOR",
       'HIGHBRIDGE GARDENS', 'GOWANUS', 'DOUGLASS ADDITION',
       'BUSHWICK II CDA (GROUP E)', 'LATIMER GARDENS',
       'CLAREMONT PARKWAY-FRANKLIN AVENUE', 'MACOMBS ROAD',
       'WSUR (SITE C) 589 AMSTER

In [7]:
nyc_crime_data['ADDR_PCT_CD'].unique()

array([ 44., 103.,  28., 105.,  13.,  71.,   7.,  46.,  48.,  19.,  41.,
        14.,  67.,  17.,  61., 102., 110., 108.,  75.,  73.,  60.,  68.,
        79., 121.,  23.,  42., 115.,  52., 122.,   1.,  72., 109.,  24.,
        81.,  90., 112.,  43.,  84.,  47.,  77., 101.,  83., 113., 120.,
        70.,  69.,  66., 114.,  76.,  63.,  45., 106.,  10.,  78.,   6.,
         5.,  94.,  40.,  34.,  32.,  50.,  25., 100.,  18.,  20., 111.,
       107.,  30.,  49.,  88.,  26., 123.,   9., 104.,  33.,  62.,  22.,
        nan])

In [8]:
nyc_crime_data['BORO_NM'].unique()

array(['BRONX', 'QUEENS', 'MANHATTAN', 'BROOKLYN', 'STATEN ISLAND', nan],
      dtype=object)

In [9]:
nyc_crime_data['LOC_OF_OCCUR_DESC'].unique()

array(['INSIDE', 'OUTSIDE', nan, 'FRONT OF', 'OPPOSITE OF', 'REAR OF',
       ' '], dtype=object)

In [10]:
nyc_crime_data['JURIS_DESC'].unique()

array(['N.Y. POLICE DEPT', 'N.Y. HOUSING POLICE', 'N.Y. TRANSIT POLICE',
       'N.Y. STATE POLICE', 'DEPT OF CORRECTIONS', 'TRI-BORO BRDG TUNNL',
       'OTHER', 'PORT AUTHORITY', 'NYC PARKS', 'HEALTH & HOSP CORP',
       'METRO NORTH', 'LONG ISLAND RAILRD', 'STATN IS RAPID TRANS',
       'N.Y. STATE PARKS', 'NEW YORK CITY SHERIFF OFFICE',
       'U.S. PARK POLICE', 'NYS DEPT TAX AND FINANCE', 'AMTRACK',
       'CONRAIL', 'POLICE DEPT NYC', 'FIRE DEPT (FIRE MARSHAL)',
       'NYC DEPT ENVIRONMENTAL PROTECTION', 'SEA GATE POLICE DEPT',
       'DISTRICT ATTORNEY OFFICE', 'NYS DEPT ENVIRONMENTAL CONSERVATION'],
      dtype=object)

In [11]:
nyc_crime_data['CRM_ATPT_CPTD_CD'].unique()

array(['COMPLETED', 'ATTEMPTED', nan], dtype=object)

In [12]:
nyc_crime_data['LAW_CAT_CD'].unique()

array(['FELONY', 'MISDEMEANOR', 'VIOLATION'], dtype=object)

In [13]:
nyc_crime_data.columns

Index(['CMPLNT_NUM', 'CMPLNT_FR_DT', 'CMPLNT_FR_TM', 'CMPLNT_TO_DT',
       'CMPLNT_TO_TM', 'RPT_DT', 'KY_CD', 'OFNS_DESC', 'PD_CD', 'PD_DESC',
       'CRM_ATPT_CPTD_CD', 'LAW_CAT_CD', 'JURIS_DESC', 'BORO_NM',
       'ADDR_PCT_CD', 'LOC_OF_OCCUR_DESC', 'PREM_TYP_DESC', 'PARKS_NM',
       'HADEVELOPT', 'X_COORD_CD', 'Y_COORD_CD', 'Latitude', 'Longitude',
       'Lat_Lon'],
      dtype='object')

In [14]:
nyc_crime_data['PD_DESC'].value_counts()

ASSAULT 3                                                 522223
HARASSMENT,SUBD 3,4,5                                     462080
AGGRAVATED HARASSMENT 2                                   322932
HARASSMENT,SUBD 1,CIVILIAN                                274407
LARCENY,PETIT FROM STORE-SHOPL                            270909
LARCENY,PETIT FROM BUILDING,UN                            260356
MISCHIEF, CRIMINAL 4, OF MOTOR                            218095
LARCENY,PETIT FROM AUTO                                   202688
MARIJUANA, POSSESSION 4 & 5                               193923
ASSAULT 2,1,UNCLASSIFIED                                  185940
CRIMINAL MISCHIEF,UNCLASSIFIED 4                          172093
LARCENY,GRAND FROM BUILDING (NON-RESIDENCE) UNATTENDED    128622
CONTROLLED SUBSTANCE, POSSESSI                            116487
CRIMINAL MISCHIEF 4TH, GRAFFIT                            111144
ROBBERY,OPEN AREA UNCLASSIFIED                            106659
LARCENY,GRAND OF AUTO    

In [15]:
# nyc_crime_data['PD_CD'].unique()

In [16]:
nyc_crime_data['OFNS_DESC'].value_counts()

PETIT LARCENY                           987326
HARRASSMENT 2                           736479
ASSAULT 3 & RELATED OFFENSES            625624
CRIMINAL MISCHIEF & RELATED OF          603977
GRAND LARCENY                           516544
DANGEROUS DRUGS                         392992
OFF. AGNST PUB ORD SENSBLTY &           327716
ROBBERY                                 228220
FELONY ASSAULT                          224921
BURGLARY                                216439
MISCELLANEOUS PENAL LAW                 145888
DANGEROUS WEAPONS                       143395
OFFENSES AGAINST PUBLIC ADMINI          117062
GRAND LARCENY OF MOTOR VEHICLE          114071
INTOXICATED & IMPAIRED DRIVING           85349
CRIMINAL TRESPASS                        74083
VEHICLE AND TRAFFIC LAWS                 72173
SEX CRIMES                               68020
THEFT-FRAUD                              66184
FORGERY                                  61024
FRAUDS                                   38308
POSSESSION OF

In [17]:
# nyc_crime_data['KY_CD'].unique()

In [18]:
nyc_crime_data['RPT_DT'].unique()

array(['12/31/2015', '12/21/2015', '12/14/2015', ..., '01/09/2017',
       '01/08/2017', '01/01/2017'], dtype=object)

In [19]:
yr=nyc_crime_data['CMPLNT_FR_DT'].str.split('/',expand=True)

In [21]:
yr.head()

0   1     2
0  12  31  2015
1  12  31  2015
2  12  31  2015
3  12  31  2015
4  12  31  2015